//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamGifCropper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamGifCropper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge 5 gif files into 1 part (766px).
        /// </summary>
        internal static string Button_MergeAndSplit {
            get {
                return ResourceManager.GetString("Button_MergeAndSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert MP4 to GIF (with time control).
        /// </summary>
        internal static string Button_Mp4ToGif {
            get {
                return ResourceManager.GetString("Button_Mp4ToGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize GIF file to 766px width.
        /// </summary>
        internal static string Button_ResizeGif {
            get {
                return ResourceManager.GetString("Button_ResizeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Gif files last byte from 0x21 to 0x3B.
        /// </summary>
        internal static string Button_RestoreTailByte {
            get {
                return ResourceManager.GetString("Button_RestoreTailByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Gif file into 5 parts with gifsicle.
        /// </summary>
        internal static string Button_SplitGif {
            get {
                return ResourceManager.GetString("Button_SplitGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Gif files last byte as 0x21.
        /// </summary>
        internal static string Button_WriteTailByte {
            get {
                return ResourceManager.GetString("Button_WriteTailByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize form: {0}.
        /// </summary>
        internal static string Error_InitializationFailed {
            get {
                return ResourceManager.GetString("Error_InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF #{0} ({1}) must have palette-based colors (8-bit).\nCurrent color type: {2}.
        /// </summary>
        internal static string Error_InvalidColorType {
            get {
                return ResourceManager.GetString("Error_InvalidColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string Error_Occurred {
            get {
                return ResourceManager.GetString("Error_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette size must be between 32 and 256..
        /// </summary>
        internal static string Error_PaletteRange {
            get {
                return ResourceManager.GetString("Error_PaletteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing five GIF merge and split: {0}.
        /// </summary>
        internal static string Error_Processing {
            get {
                return ResourceManager.GetString("Error_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing {0}: {1}.
        /// </summary>
        internal static string Error_ProcessingFile {
            get {
                return ResourceManager.GetString("Error_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize operation failed: {0}.
        /// </summary>
        internal static string Error_ResizeFailed {
            get {
                return ResourceManager.GetString("Error_ResizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application startup failed: {0}\n\nStack trace:\n{1}.
        /// </summary>
        internal static string Error_StartupFailed {
            get {
                return ResourceManager.GetString("Error_StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nStack trace:\n{1}.
        /// </summary>
        internal static string Error_UnhandledException {
            get {
                return ResourceManager.GetString("Error_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported GIF canvas width: {0}px. Only {1}px and {2}px are supported..
        /// </summary>
        internal static string Error_UnsupportedWidth {
            get {
                return ResourceManager.GetString("Error_UnsupportedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (*.gif)|*.gif.
        /// </summary>
        internal static string FileDialog_GifFilter {
            get {
                return ResourceManager.GetString("FileDialog_GifFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a GIF file to process.
        /// </summary>
        internal static string FileDialog_SelectGif {
            get {
                return ResourceManager.GetString("FileDialog_SelectGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF files to process.
        /// </summary>
        internal static string FileDialog_SelectGifFiles {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF file #{0} (position {1} from left to right).
        /// </summary>
        internal static string FileDialog_SelectGifOrder {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF files to restore tail bytes from 0x21 to 0x3B.
        /// </summary>
        internal static string FileDialog_SelectGifRestore {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a GIF file to resize.
        /// </summary>
        internal static string FileDialog_SelectGifResize {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dither.
        /// </summary>
        internal static string Group_Dither {
            get {
                return ResourceManager.GetString("Group_Dither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to select 5 GIF files one by one in the desired order.\n\nFile 1: First position (leftmost)\nFile 2: Second position\nFile 3: Third position (center)\nFile 4: Fourth position\nFile 5: Fifth position (rightmost).
        /// </summary>
        internal static string Instruction_SelectFiveGifs {
            get {
                return ResourceManager.GetString("Instruction_SelectFiveGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossy:.
        /// </summary>
        internal static string Label_Lossy {
            get {
                return ResourceManager.GetString("Label_Lossy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize:.
        /// </summary>
        internal static string Label_Optimize {
            get {
                return ResourceManager.GetString("Label_Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        internal static string Label_Palette {
            get {
                return ResourceManager.GetString("Label_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        internal static string Label_Framerate {
            get {
                return ResourceManager.GetString("Label_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fps.
        /// </summary>
        internal static string Label_FPS {
            get {
                return ResourceManager.GetString("Label_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target framerate for all GIF outputs (frames per second).
        /// </summary>
        internal static string Tooltip_Framerate {
            get {
                return ResourceManager.GetString("Tooltip_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five GIF files have been merged and split into 5 parts successfully!.
        /// </summary>
        internal static string Message_FiveGifMergeComplete {
            get {
                return ResourceManager.GetString("Message_FiveGifMergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Message_Mp4ConversionComplete {
            get {
                return ResourceManager.GetString("Message_Mp4ConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF processing with reduced palette completed successfully!.
        /// </summary>
        internal static string Message_PaletteProcessingComplete {
            get {
                return ResourceManager.GetString("Message_PaletteProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} GIF files processed successfully!.
        /// </summary>
        internal static string Message_ProcessedFiles {
            get {
                return ResourceManager.GetString("Message_ProcessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF processing and splitting completed successfully!.
        /// </summary>
        internal static string Message_ProcessingComplete {
            get {
                return ResourceManager.GetString("Message_ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF resizing completed successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Message_ResizeComplete {
            get {
                return ResourceManager.GetString("Message_ResizeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration completed!\nFiles processed: {0}\nFiles skipped (not 0x21): {1}.
        /// </summary>
        internal static string Message_RestorationComplete {
            get {
                return ResourceManager.GetString("Message_RestorationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Mp4Dialog_Duration {
            get {
                return ResourceManager.GetString("Mp4Dialog_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input MP4 file:.
        /// </summary>
        internal static string Mp4Dialog_InputFile {
            get {
                return ResourceManager.GetString("Mp4Dialog_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min:.
        /// </summary>
        internal static string Mp4Dialog_Minutes {
            get {
                return ResourceManager.GetString("Mp4Dialog_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output GIF file:.
        /// </summary>
        internal static string Mp4Dialog_OutputFile {
            get {
                return ResourceManager.GetString("Mp4Dialog_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec:.
        /// </summary>
        internal static string Mp4Dialog_Seconds {
            get {
                return ResourceManager.GetString("Mp4Dialog_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string Mp4Dialog_StartTime {
            get {
                return ResourceManager.GetString("Mp4Dialog_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPU acceleration (if available).
        /// </summary>
        internal static string Mp4Dialog_UseGPU {
            get {
                return ResourceManager.GetString("Mp4Dialog_UseGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Radio_Default {
            get {
                return ResourceManager.GetString("Radio_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Radio_None {
            get {
                return ResourceManager.GetString("Radio_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o8.
        /// </summary>
        internal static string Radio_o8 {
            get {
                return ResourceManager.GetString("Radio_o8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro64.
        /// </summary>
        internal static string Radio_ro64 {
            get {
                return ResourceManager.GetString("Radio_ro64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coalescing frames....
        /// </summary>
        internal static string Status_CoalescingFrames {
            get {
                return ResourceManager.GetString("Status_CoalescingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing....
        /// </summary>
        internal static string Status_Compressing {
            get {
                return ResourceManager.GetString("Status_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during processing..
        /// </summary>
        internal static string Status_ErrorOccurred {
            get {
                return ResourceManager.GetString("Status_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five GIF merge and split completed successfully!.
        /// </summary>
        internal static string Status_FiveGifComplete {
            get {
                return ResourceManager.GetString("Status_FiveGifComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifsicle-ing....
        /// </summary>
        internal static string Status_GifsicleOptimizing {
            get {
                return ResourceManager.GetString("Status_GifsicleOptimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle..
        /// </summary>
        internal static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging frame {0}/{1}....
        /// </summary>
        internal static string Status_MergingFrame {
            get {
                return ResourceManager.GetString("Status_MergingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging GIFs horizontally to 766px width....
        /// </summary>
        internal static string Status_MergingHorizontally {
            get {
                return ResourceManager.GetString("Status_MergingHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting MP4 to GIF with optimized CPU....
        /// </summary>
        internal static string Status_Mp4CPU {
            get {
                return ResourceManager.GetString("Status_Mp4CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!.
        /// </summary>
        internal static string Status_Mp4Complete {
            get {
                return ResourceManager.GetString("Status_Mp4Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode + CPU GIF encoding....
        /// </summary>
        internal static string Status_Mp4GPU {
            get {
                return ResourceManager.GetString("Status_Mp4GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode failed, using CPU....
        /// </summary>
        internal static string Status_Mp4GPUFailed {
            get {
                return ResourceManager.GetString("Status_Mp4GPUFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short clip - CPU more efficient....
        /// </summary>
        internal static string Status_Mp4ShortClip {
            get {
                return ResourceManager.GetString("Status_Mp4ShortClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing....
        /// </summary>
        internal static string Status_Optimizing {
            get {
                return ResourceManager.GetString("Status_Optimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing... {0}/{1}.
        /// </summary>
        internal static string Status_ProcessingCount {
            get {
                return ResourceManager.GetString("Status_ProcessingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing with reduced palette....
        /// </summary>
        internal static string Status_ProcessingPalette {
            get {
                return ResourceManager.GetString("Status_ProcessingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing part {0}, frame {1}....
        /// </summary>
        internal static string Status_ProcessingPart {
            get {
                return ResourceManager.GetString("Status_ProcessingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing part {0} with palette reduction, frame {1}....
        /// </summary>
        internal static string Status_ProcessingPartPalette {
            get {
                return ResourceManager.GetString("Status_ProcessingPartPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing frames....
        /// </summary>
        internal static string Status_ResizingFrames {
            get {
                return ResourceManager.GetString("Status_ResizingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing GIF #{0} to {1}px width....
        /// </summary>
        internal static string Status_ResizingGif {
            get {
                return ResourceManager.GetString("Status_ResizingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing GIF #{0} - Frame {1}/{2}....
        /// </summary>
        internal static string Status_ResizingGifFrame {
            get {
                return ResourceManager.GetString("Status_ResizingGifFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring tail bytes....
        /// </summary>
        internal static string Status_RestoringTailBytes {
            get {
                return ResourceManager.GetString("Status_RestoringTailBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest duration: {0:F1}s (GIF #{1}).
        /// </summary>
        internal static string Status_ShortestDuration {
            get {
                return ResourceManager.GetString("Status_ShortestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing animation durations....
        /// </summary>
        internal static string Status_SynchronizingDurations {
            get {
                return ResourceManager.GetString("Status_SynchronizingDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing GIF #{0} duration....
        /// </summary>
        internal static string Status_SynchronizingGif {
            get {
                return ResourceManager.GetString("Status_SynchronizingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating and processing 5 GIF files....
        /// </summary>
        internal static string Status_ValidatingProcessing {
            get {
                return ResourceManager.GetString("Status_ValidatingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Required.
        /// </summary>
        internal static string Title_FFmpegRequired {
            get {
                return ResourceManager.GetString("Title_FFmpegRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Processing Error.
        /// </summary>
        internal static string Title_FileProcessingError {
            get {
                return ResourceManager.GetString("Title_FileProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Error.
        /// </summary>
        internal static string Title_InitializationError {
            get {
                return ResourceManager.GetString("Title_InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Color Type.
        /// </summary>
        internal static string Title_InvalidColorType {
            get {
                return ResourceManager.GetString("Title_InvalidColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF Conversion Error.
        /// </summary>
        internal static string Title_Mp4ToGifError {
            get {
                return ResourceManager.GetString("Title_Mp4ToGifError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Order Information.
        /// </summary>
        internal static string Title_SelectionOrder {
            get {
                return ResourceManager.GetString("Title_SelectionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string Title_StartupError {
            get {
                return ResourceManager.GetString("Title_StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail Byte Restoration.
        /// </summary>
        internal static string Title_TailByteRestoration {
            get {
                return ResourceManager.GetString("Title_TailByteRestoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
    }
}