//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamGifCropper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamGifCropper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge 5 gif files into 1 part (766px).
        /// </summary>
        internal static string Button_MergeAndSplit {
            get {
                return ResourceManager.GetString("Button_MergeAndSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert MP4 to GIF (with time control).
        /// </summary>
        internal static string Button_Mp4ToGif {
            get {
                return ResourceManager.GetString("Button_Mp4ToGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge 2-5 GIF files into one.
        /// </summary>
        internal static string Button_MergeGifs {
            get {
                return ResourceManager.GetString("Button_MergeGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize GIF file to 766px width.
        /// </summary>
        internal static string Button_ResizeGif {
            get {
                return ResourceManager.GetString("Button_ResizeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Gif files last byte from 0x21 to 0x3B.
        /// </summary>
        internal static string Button_RestoreTailByte {
            get {
                return ResourceManager.GetString("Button_RestoreTailByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Gif file into 5 parts with gifsicle.
        /// </summary>
        internal static string Button_SplitGif {
            get {
                return ResourceManager.GetString("Button_SplitGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Gif files last byte as 0x21.
        /// </summary>
        internal static string Button_WriteTailByte {
            get {
                return ResourceManager.GetString("Button_WriteTailByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize form: {0}.
        /// </summary>
        internal static string Error_InitializationFailed {
            get {
                return ResourceManager.GetString("Error_InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF #{0} ({1}) must have palette-based colors (8-bit).\nCurrent color type: {2}.
        /// </summary>
        internal static string Error_InvalidColorType {
            get {
                return ResourceManager.GetString("Error_InvalidColorType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insufficient cache resources. Reduce image size or increase memory/disk limits.
        /// </summary>
        internal static string Error_CacheResourcesExhausted {
            get {
                return ResourceManager.GetString("Error_CacheResourcesExhausted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string Error_Occurred {
            get {
                return ResourceManager.GetString("Error_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette size must be between 32 and 256..
        /// </summary>
        internal static string Error_PaletteRange {
            get {
                return ResourceManager.GetString("Error_PaletteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing five GIF merge and split: {0}.
        /// </summary>
        internal static string Error_Processing {
            get {
                return ResourceManager.GetString("Error_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing {0}: {1}.
        /// </summary>
        internal static string Error_ProcessingFile {
            get {
                return ResourceManager.GetString("Error_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize operation failed: {0}.
        /// </summary>
        internal static string Error_ResizeFailed {
            get {
                return ResourceManager.GetString("Error_ResizeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a GIF file.
        /// </summary>
        internal static string Error_SelectGif {
            get {
                return ResourceManager.GetString("Error_SelectGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application startup failed: {0}\n\nStack trace:\n{1}.
        /// </summary>
        internal static string Error_StartupFailed {
            get {
                return ResourceManager.GetString("Error_StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nStack trace:\n{1}.
        /// </summary>
        internal static string Error_UnhandledException {
            get {
                return ResourceManager.GetString("Error_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported GIF canvas width: {0}px. Only {1}px and {2}px are supported..
        /// </summary>
        internal static string Error_UnsupportedWidth {
            get {
                return ResourceManager.GetString("Error_UnsupportedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (*.gif)|*.gif.
        /// </summary>
        internal static string FileDialog_GifFilter {
            get {
                return ResourceManager.GetString("FileDialog_GifFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a GIF file to process.
        /// </summary>
        internal static string FileDialog_SelectGif {
            get {
                return ResourceManager.GetString("FileDialog_SelectGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF files to process.
        /// </summary>
        internal static string FileDialog_SelectGifFiles {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF file #{0} (position {1} from left to right).
        /// </summary>
        internal static string FileDialog_SelectGifOrder {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF files to restore tail bytes from 0x21 to 0x3B.
        /// </summary>
        internal static string FileDialog_SelectGifRestore {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a GIF file to resize.
        /// </summary>
        internal static string FileDialog_SelectGifResize {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dither.
        /// </summary>
        internal static string Group_Dither {
            get {
                return ResourceManager.GetString("Group_Dither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to select 5 GIF files one by one in the desired order.\n\nFile 1: First position (leftmost)\nFile 2: Second position\nFile 3: Third position (center)\nFile 4: Fourth position\nFile 5: Fifth position (rightmost).
        /// </summary>
        internal static string Instruction_SelectFiveGifs {
            get {
                return ResourceManager.GetString("Instruction_SelectFiveGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossy:.
        /// </summary>
        internal static string Label_Lossy {
            get {
                return ResourceManager.GetString("Label_Lossy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize:.
        /// </summary>
        internal static string Label_Optimize {
            get {
                return ResourceManager.GetString("Label_Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        internal static string Label_Palette {
            get {
                return ResourceManager.GetString("Label_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        internal static string Label_Framerate {
            get {
                return ResourceManager.GetString("Label_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fps for split GIF.
        /// </summary>
        internal static string Label_FPS {
            get {
                return ResourceManager.GetString("Label_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target framerate for all GIF outputs (frames per second).
        /// </summary>
        internal static string Tooltip_Framerate {
            get {
                return ResourceManager.GetString("Tooltip_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster palette reduction (quality down).
        /// </summary>
        internal static string CheckBox_FasterPalette {
            get {
                return ResourceManager.GetString("CheckBox_FasterPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMPEG: Reverse animated GIF.
        /// </summary>
        internal static string Button_ReverseGif {
            get {
                return ResourceManager.GetString("Button_ReverseGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five GIF files have been merged and split into 5 parts successfully!.
        /// </summary>
        internal static string Message_FiveGifMergeComplete {
            get {
                return ResourceManager.GetString("Message_FiveGifMergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF files merged successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Message_GifMergeComplete {
            get {
                return ResourceManager.GetString("Message_GifMergeComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Five GIF merge and split completed successfully!.
        /// </summary>
        internal static string MergeFiveGif_Success {
            get {
                return ResourceManager.GetString("MergeFiveGif_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error occurred during processing..
        /// </summary>
        internal static string MergeFiveGif_Error {
            get {
                return ResourceManager.GetString("MergeFiveGif_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select 2-5 GIF files to merge (in order from left to right):.
        /// </summary>
        internal static string Message_SelectGifFiles {
            get {
                return ResourceManager.GetString("Message_SelectGifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select between 2 and 5 GIF files..
        /// </summary>
        internal static string Message_GifFileCount {
            get {
                return ResourceManager.GetString("Message_GifFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing GIF files....
        /// </summary>
        internal static string Message_AnalyzingGifs {
            get {
                return ResourceManager.GetString("Message_AnalyzingGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging GIF files....
        /// </summary>
        internal static string Message_MergingGifs {
            get {
                return ResourceManager.GetString("Message_MergingGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Message_Mp4ConversionComplete {
            get {
                return ResourceManager.GetString("Message_Mp4ConversionComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlay complete..
        /// </summary>
        internal static string Message_OverlayComplete {
            get {
                return ResourceManager.GetString("Message_OverlayComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF processing with reduced palette completed successfully!.
        /// </summary>
        internal static string Message_PaletteProcessingComplete {
            get {
                return ResourceManager.GetString("Message_PaletteProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} GIF files processed successfully!.
        /// </summary>
        internal static string Message_ProcessedFiles {
            get {
                return ResourceManager.GetString("Message_ProcessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF processing and splitting completed successfully!.
        /// </summary>
        internal static string Message_ProcessingComplete {
            get {
                return ResourceManager.GetString("Message_ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF resizing completed successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Message_ResizeComplete {
            get {
                return ResourceManager.GetString("Message_ResizeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration completed!\nFiles processed: {0}\nFiles skipped (not 0x21): {1}.
        /// </summary>
        internal static string Message_RestorationComplete {
            get {
                return ResourceManager.GetString("Message_RestorationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Mp4Dialog_Duration {
            get {
                return ResourceManager.GetString("Mp4Dialog_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input MP4 file:.
        /// </summary>
        internal static string Mp4Dialog_InputFile {
            get {
                return ResourceManager.GetString("Mp4Dialog_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min:.
        /// </summary>
        internal static string Mp4Dialog_Minutes {
            get {
                return ResourceManager.GetString("Mp4Dialog_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output GIF file:.
        /// </summary>
        internal static string Mp4Dialog_OutputFile {
            get {
                return ResourceManager.GetString("Mp4Dialog_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec:.
        /// </summary>
        internal static string Mp4Dialog_Seconds {
            get {
                return ResourceManager.GetString("Mp4Dialog_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string Mp4Dialog_StartTime {
            get {
                return ResourceManager.GetString("Mp4Dialog_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPU acceleration (if available).
        /// </summary>
        internal static string Mp4Dialog_UseGPU {
            get {
                return ResourceManager.GetString("Mp4Dialog_UseGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Radio_Default {
            get {
                return ResourceManager.GetString("Radio_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Radio_None {
            get {
                return ResourceManager.GetString("Radio_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o8.
        /// </summary>
        internal static string Radio_o8 {
            get {
                return ResourceManager.GetString("Radio_o8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro64.
        /// </summary>
        internal static string Radio_ro64 {
            get {
                return ResourceManager.GetString("Radio_ro64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coalescing frames....
        /// </summary>
        internal static string Status_CoalescingFrames {
            get {
                return ResourceManager.GetString("Status_CoalescingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing....
        /// </summary>
        internal static string Status_Compressing {
            get {
                return ResourceManager.GetString("Status_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during processing..
        /// </summary>
        internal static string Status_ErrorOccurred {
            get {
                return ResourceManager.GetString("Status_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five GIF merge and split completed successfully!.
        /// </summary>
        internal static string Status_FiveGifComplete {
            get {
                return ResourceManager.GetString("Status_FiveGifComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifsicle-ing....
        /// </summary>
        internal static string Status_GifsicleOptimizing {
            get {
                return ResourceManager.GetString("Status_GifsicleOptimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle..
        /// </summary>
        internal static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlaying....
        /// </summary>
        internal static string Status_Overlaying {
            get {
                return ResourceManager.GetString("Status_Overlaying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mapping with fast palette....
        /// </summary>
        internal static string Status_MappingFastPalette {
            get {
                return ResourceManager.GetString("Status_MappingFastPalette", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mapping to shared palette....
        /// </summary>
        internal static string Status_MappingSharedPalette {
            get {
                return ResourceManager.GetString("Status_MappingSharedPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging frame {0}/{1}....
        /// </summary>
        internal static string Status_MergingFrame {
            get {
                return ResourceManager.GetString("Status_MergingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging GIFs horizontally to 766px width....
        /// </summary>
        internal static string Status_MergingHorizontally {
            get {
                return ResourceManager.GetString("Status_MergingHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting MP4 to GIF with optimized CPU....
        /// </summary>
        internal static string Status_Mp4CPU {
            get {
                return ResourceManager.GetString("Status_Mp4CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!.
        /// </summary>
        internal static string Status_Mp4Complete {
            get {
                return ResourceManager.GetString("Status_Mp4Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode + CPU GIF encoding....
        /// </summary>
        internal static string Status_Mp4GPU {
            get {
                return ResourceManager.GetString("Status_Mp4GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode failed, using CPU....
        /// </summary>
        internal static string Status_Mp4GPUFailed {
            get {
                return ResourceManager.GetString("Status_Mp4GPUFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short clip - CPU more efficient....
        /// </summary>
        internal static string Status_Mp4ShortClip {
            get {
                return ResourceManager.GetString("Status_Mp4ShortClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing....
        /// </summary>
        internal static string Status_Optimizing {
            get {
                return ResourceManager.GetString("Status_Optimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing... {0}/{1}.
        /// </summary>
        internal static string Status_ProcessingCount {
            get {
                return ResourceManager.GetString("Status_ProcessingCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing frame {0}/{1}.
        /// </summary>
        internal static string Status_ProcessingFrame {
            get {
                return ResourceManager.GetString("Status_ProcessingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing with reduced palette....
        /// </summary>
        internal static string Status_ProcessingPalette {
            get {
                return ResourceManager.GetString("Status_ProcessingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing part {0}, frame {1}....
        /// </summary>
        internal static string Status_ProcessingPart {
            get {
                return ResourceManager.GetString("Status_ProcessingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing part {0} with palette reduction, frame {1}....
        /// </summary>
        internal static string Status_ProcessingPartPalette {
            get {
                return ResourceManager.GetString("Status_ProcessingPartPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing frames....
        /// </summary>
        internal static string Status_ResizingFrames {
            get {
                return ResourceManager.GetString("Status_ResizingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing GIF #{0} to {1}px width....
        /// </summary>
        internal static string Status_ResizingGif {
            get {
                return ResourceManager.GetString("Status_ResizingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing GIF #{0} - Frame {1}/{2}....
        /// </summary>
        internal static string Status_ResizingGifFrame {
            get {
                return ResourceManager.GetString("Status_ResizingGifFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring tail bytes....
        /// </summary>
        internal static string Status_RestoringTailBytes {
            get {
                return ResourceManager.GetString("Status_RestoringTailBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducing palette....
        /// </summary>
        internal static string Status_ReducingPalette {
            get {
                return ResourceManager.GetString("Status_ReducingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest duration: {0:F1}s (GIF #{1}).
        /// </summary>
        internal static string Status_ShortestDuration {
            get {
                return ResourceManager.GetString("Status_ShortestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing animation durations....
        /// </summary>
        internal static string Status_SynchronizingDurations {
            get {
                return ResourceManager.GetString("Status_SynchronizingDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing GIF #{0} duration....
        /// </summary>
        internal static string Status_SynchronizingGif {
            get {
                return ResourceManager.GetString("Status_SynchronizingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating and processing 5 GIF files....
        /// </summary>
        internal static string Status_ValidatingProcessing {
            get {
                return ResourceManager.GetString("Status_ValidatingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Required.
        /// </summary>
        internal static string Title_FFmpegRequired {
            get {
                return ResourceManager.GetString("Title_FFmpegRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Processing Error.
        /// </summary>
        internal static string Title_FileProcessingError {
            get {
                return ResourceManager.GetString("Title_FileProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Error.
        /// </summary>
        internal static string Title_InitializationError {
            get {
                return ResourceManager.GetString("Title_InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Color Type.
        /// </summary>
        internal static string Title_InvalidColorType {
            get {
                return ResourceManager.GetString("Title_InvalidColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF Conversion Error.
        /// </summary>
        internal static string Title_Mp4ToGifError {
            get {
                return ResourceManager.GetString("Title_Mp4ToGifError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge GIF Files.
        /// </summary>
        internal static string Title_MergeGifs {
            get {
                return ResourceManager.GetString("Title_MergeGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Merge Error.
        /// </summary>
        internal static string Title_MergeGifError {
            get {
                return ResourceManager.GetString("Title_MergeGifError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Order Information.
        /// </summary>
        internal static string Title_SelectionOrder {
            get {
                return ResourceManager.GetString("Title_SelectionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string Title_StartupError {
            get {
                return ResourceManager.GetString("Title_StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail Byte Restoration.
        /// </summary>
        internal static string Title_TailByteRestoration {
            get {
                return ResourceManager.GetString("Title_TailByteRestoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a GIF file to reverse.
        /// </summary>
        internal static string FileDialog_SelectGifToReverse {
            get {
                return ResourceManager.GetString("FileDialog_SelectGifToReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save reversed GIF as.
        /// </summary>
        internal static string FileDialog_SaveReversedGif {
            get {
                return ResourceManager.GetString("FileDialog_SaveReversedGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing GIF....
        /// </summary>
        internal static string Status_ReversingGif {
            get {
                return ResourceManager.GetString("Status_ReversingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF reversed successfully!.
        /// </summary>
        internal static string Status_GifReversed {
            get {
                return ResourceManager.GetString("Status_GifReversed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFmpeg failed, trying ImageMagick fallback....
        /// </summary>
        internal static string Status_FFmpegFallback {
            get {
                return ResourceManager.GetString("Status_FFmpegFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF reversed successfully!.
        /// </summary>
        internal static string Message_GifReversedSuccess {
            get {
                return ResourceManager.GetString("Message_GifReversedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reverse GIF: {0}.
        /// </summary>
        internal static string Error_GifReverseFailed {
            get {
                return ResourceManager.GetString("Error_GifReverseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable gifsicle optimization.
        /// </summary>
        internal static string CheckBox_GifsicleOptimization {
            get {
                return ResourceManager.GetString("CheckBox_GifsicleOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice: gifsicle.exe must be in "System Path".
        /// </summary>
        internal static string Label_GifsicleNotice {
            get {
                return ResourceManager.GetString("Label_GifsicleNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource limit: mem: {0} MB / disk: {1} MB.
        /// </summary>
        internal static string Label_ResourceLimitDesc {
            get {
                return ResourceManager.GetString("Label_ResourceLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 2-5 GIF files to merge (in order from left to right):.
        /// </summary>
        internal static string MergeDialog_Instructions {
            get {
                return ResourceManager.GetString("MergeDialog_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (2-5):.
        /// </summary>
        internal static string MergeDialog_GifFiles {
            get {
                return ResourceManager.GetString("MergeDialog_GifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        internal static string MergeDialog_AddFiles {
            get {
                return ResourceManager.GetString("MergeDialog_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MergeDialog_Remove {
            get {
                return ResourceManager.GetString("MergeDialog_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MergeDialog_MoveUp {
            get {
                return ResourceManager.GetString("MergeDialog_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MergeDialog_MoveDown {
            get {
                return ResourceManager.GetString("MergeDialog_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output GIF file:.
        /// </summary>
        internal static string MergeDialog_OutputFile {
            get {
                return ResourceManager.GetString("MergeDialog_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string MergeDialog_Merge {
            get {
                return ResourceManager.GetString("MergeDialog_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MergeDialog_Cancel {
            get {
                return ResourceManager.GetString("MergeDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge GIF Files.
        /// </summary>
        internal static string MergeDialog_Title {
            get {
                return ResourceManager.GetString("MergeDialog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string MergeDialog_FileNotFound {
            get {
                return ResourceManager.GetString("MergeDialog_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please specify an output GIF file..
        /// </summary>
        internal static string MergeDialog_RequireOutput {
            get {
                return ResourceManager.GetString("MergeDialog_RequireOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot create output directory:.
        /// </summary>
        internal static string MergeDialog_CannotCreateDir {
            get {
                return ResourceManager.GetString("MergeDialog_CannotCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette source:.
        /// </summary>
        internal static string MergeDialog_PaletteSource {
            get {
                return ResourceManager.GetString("MergeDialog_PaletteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GIF files to merge.
        /// </summary>
        internal static string MergeDialog_SelectGifFiles {
            get {
                return ResourceManager.GetString("MergeDialog_SelectGifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save merged GIF as....
        /// </summary>
        internal static string MergeDialog_SaveMergedGif {
            get {
                return ResourceManager.GetString("MergeDialog_SaveMergedGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (*.gif)|*.gif.
        /// </summary>
        internal static string MergeDialog_GifFilter {
            get {
                return ResourceManager.GetString("MergeDialog_GifFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF {0}: {1}.
        /// </summary>
        internal static string MergeDialog_GifNumberFormat {
            get {
                return ResourceManager.GetString("MergeDialog_GifNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select exactly 5 GIF files to merge and split (in order from left to right):.
        /// </summary>
        internal static string MergeFiveGifDialog_Instructions {
            get {
                return ResourceManager.GetString("MergeFiveGifDialog_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (exactly 5):.
        /// </summary>
        internal static string MergeFiveGifDialog_GifFiles {
            get {
                return ResourceManager.GetString("MergeFiveGifDialog_GifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge 5 GIF Files.
        /// </summary>
        internal static string MergeFiveGifDialog_Title {
            get {
                return ResourceManager.GetString("MergeFiveGifDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of 5 GIF files allowed..
        /// </summary>
        internal static string MergeFiveGifDialog_MaxFiles {
            get {
                return ResourceManager.GetString("MergeFiveGifDialog_MaxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select exactly 5 GIF files..
        /// </summary>
        internal static string MergeFiveGifDialog_RequireExactly5 {
            get {
                return ResourceManager.GetString("MergeFiveGifDialog_RequireExactly5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input MP4 file:.
        /// </summary>
        internal static string Mp4Dialog_InputLabel {
            get {
                return ResourceManager.GetString("Mp4Dialog_InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Mp4Dialog_Browse {
            get {
                return ResourceManager.GetString("Mp4Dialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output GIF file:.
        /// </summary>
        internal static string Mp4Dialog_OutputLabel {
            get {
                return ResourceManager.GetString("Mp4Dialog_OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string Mp4Dialog_StartTimeLabel {
            get {
                return ResourceManager.GetString("Mp4Dialog_StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min:.
        /// </summary>
        internal static string Mp4Dialog_Min {
            get {
                return ResourceManager.GetString("Mp4Dialog_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec:.
        /// </summary>
        internal static string Mp4Dialog_Sec {
            get {
                return ResourceManager.GetString("Mp4Dialog_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms:.
        /// </summary>
        internal static string Mp4Dialog_Ms {
            get {
                return ResourceManager.GetString("Mp4Dialog_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (max 30s):.
        /// </summary>
        internal static string Mp4Dialog_DurationLabel {
            get {
                return ResourceManager.GetString("Mp4Dialog_DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Mp4Dialog_Convert {
            get {
                return ResourceManager.GetString("Mp4Dialog_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Mp4Dialog_Cancel {
            get {
                return ResourceManager.GetString("Mp4Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to install FFmpeg? (Required for MP4 conversion).
        /// </summary>
        internal static string Mp4Dialog_FFmpegHelp {
            get {
                return ResourceManager.GetString("Mp4Dialog_FFmpegHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode (decode only, GIF encode uses CPU).
        /// </summary>
        internal static string Mp4Dialog_GPUDecode {
            get {
                return ResourceManager.GetString("Mp4Dialog_GPUDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking GPU....
        /// </summary>
        internal static string Mp4Dialog_CheckingGPU {
            get {
                return ResourceManager.GetString("Mp4Dialog_CheckingGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF Converter.
        /// </summary>
        internal static string Mp4Dialog_Title {
            get {
                return ResourceManager.GetString("Mp4Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA GPU detected ✓.
        /// </summary>
        internal static string Mp4Dialog_NvidiaDetected {
            get {
                return ResourceManager.GetString("Mp4Dialog_NvidiaDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NVIDIA GPU detected.
        /// </summary>
        internal static string Mp4Dialog_NoNvidiaGPU {
            get {
                return ResourceManager.GetString("Mp4Dialog_NoNvidiaGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU detection failed.
        /// </summary>
        internal static string Mp4Dialog_GPUDetectionFailed {
            get {
                return ResourceManager.GetString("Mp4Dialog_GPUDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU decode enabled ⚡.
        /// </summary>
        internal static string Mp4Dialog_GPUEnabled {
            get {
                return ResourceManager.GetString("Mp4Dialog_GPUEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA GPU detected (CPU decode) ✓.
        /// </summary>
        internal static string Mp4Dialog_NvidiaGPUCPU {
            get {
                return ResourceManager.GetString("Mp4Dialog_NvidiaGPUCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use MP4 to GIF conversion, you need to install FFmpeg first....
        /// </summary>
        internal static string Mp4Dialog_FFmpegMessage {
            get {
                return ResourceManager.GetString("Mp4Dialog_FFmpegMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Installation Guide.
        /// </summary>
        internal static string Mp4Dialog_FFmpegGuideTitle {
            get {
                return ResourceManager.GetString("Mp4Dialog_FFmpegGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an input MP4 file..
        /// </summary>
        internal static string Mp4Dialog_SelectInputFile {
            get {
                return ResourceManager.GetString("Mp4Dialog_SelectInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Required.
        /// </summary>
        internal static string Mp4Dialog_InputRequired {
            get {
                return ResourceManager.GetString("Mp4Dialog_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file does not exist..
        /// </summary>
        internal static string Mp4Dialog_FileNotFound {
            get {
                return ResourceManager.GetString("Mp4Dialog_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string Mp4Dialog_FileNotFoundTitle {
            get {
                return ResourceManager.GetString("Mp4Dialog_FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an output GIF file..
        /// </summary>
        internal static string Mp4Dialog_SpecifyOutput {
            get {
                return ResourceManager.GetString("Mp4Dialog_SpecifyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Required.
        /// </summary>
        internal static string Mp4Dialog_OutputRequired {
            get {
                return ResourceManager.GetString("Mp4Dialog_OutputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create output directory:.
        /// </summary>
        internal static string Mp4Dialog_CannotCreateDir {
            get {
                return ResourceManager.GetString("Mp4Dialog_CannotCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Error.
        /// </summary>
        internal static string Mp4Dialog_DirectoryError {
            get {
                return ResourceManager.GetString("Mp4Dialog_DirectoryError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFmpeg is not installed or not available in the system PATH.\n\nFFmpeg Path: {0}\nVersion: {1}\n{2}\n\nTo install FFmpeg:\n1. Open Command Prompt or PowerShell as Administrator\n2. Run: winget install ffmpeg\n3. Restart this application\n\nFor more help, click the link in the MP4 to GIF dialog..
        /// </summary>
        internal static string Mp4ToGif_FFmpegRequiredMessage {
            get {
                return ResourceManager.GetString("Mp4ToGif_FFmpegRequiredMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Short clip - CPU more efficient....
        /// </summary>
        internal static string Mp4ToGif_ShortClipCpu {
            get {
                return ResourceManager.GetString("Mp4ToGif_ShortClipCpu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GPU decode + CPU GIF encoding....
        /// </summary>
        internal static string Mp4ToGif_GpuCpuEncoding {
            get {
                return ResourceManager.GetString("Mp4ToGif_GpuCpuEncoding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GPU decode failed, using CPU....
        /// </summary>
        internal static string Mp4ToGif_GpuDecodeFailed {
            get {
                return ResourceManager.GetString("Mp4ToGif_GpuDecodeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (FFmpeg log: {0}).
        /// </summary>
        internal static string Mp4ToGif_FFmpegLog {
            get {
                return ResourceManager.GetString("Mp4ToGif_FFmpegLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  FFmpeg output: {0}.
        /// </summary>
        internal static string Mp4ToGif_FFmpegOutput {
            get {
                return ResourceManager.GetString("Mp4ToGif_FFmpegOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Converting MP4 to GIF with optimized CPU....
        /// </summary>
        internal static string Mp4ToGif_Converting {
            get {
                return ResourceManager.GetString("Mp4ToGif_Converting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!.
        /// </summary>
        internal static string Mp4ToGif_Success {
            get {
                return ResourceManager.GetString("Mp4ToGif_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MP4 to GIF conversion completed successfully!\nSaved as: {0}.
        /// </summary>
        internal static string Mp4ToGif_SuccessMessage {
            get {
                return ResourceManager.GetString("Mp4ToGif_SuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFmpeg executable not found. Please ensure FFmpeg is installed and available in your system PATH.\n\nInstallation: winget install ffmpeg.
        /// </summary>
        internal static string Mp4ToGif_Error_FFmpegNotFound {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_FFmpegNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The input video file appears to be corrupted or incomplete.\n\nTry using a different video file or re-download the original..
        /// </summary>
        internal static string Mp4ToGif_Error_CorruptedInput {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_CorruptedInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GPU acceleration failed. The conversion will automatically retry with CPU processing.\n\nThis is normal if your GPU drivers are outdated or CUDA is not properly installed..
        /// </summary>
        internal static string Mp4ToGif_Error_GPUFailed {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_GPUFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot access the output directory. Please check file permissions and ensure the directory is writable..
        /// </summary>
        internal static string Mp4ToGif_Error_PermissionDenied {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_PermissionDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during MP4 to GIF conversion..
        /// </summary>
        internal static string Mp4ToGif_Error_Unexpected {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_Unexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to \n\nDetailed FFmpeg output saved to: {0}.
        /// </summary>
        internal static string Mp4ToGif_Error_DetailsSaved {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_DetailsSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to \n\nFFmpeg output (truncated):\n{0}.
        /// </summary>
        internal static string Mp4ToGif_Error_FFmpegOutputTruncated {
            get {
                return ResourceManager.GetString("Mp4ToGif_Error_FFmpegOutputTruncated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}\n\nInput file: "{1}"\nOutput file: "{2}"\nStart time: {3}\nDuration: {4}\n\nTechnical details: {5}.
        /// </summary>
        internal static string Mp4ToGif_ErrorMessageDetails {
            get {
                return ResourceManager.GetString("Mp4ToGif_ErrorMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 Files (*.mp4)|*.mp4|All Video Files|*.mp4;*.avi;*.mkv;*.mov.
        /// </summary>
        internal static string FileDialog_Mp4Filter {
            get {
                return ResourceManager.GetString("FileDialog_Mp4Filter", resourceCulture);
            }
        }

        internal static string FileDialog_SelectMp4 {
            get {
                return ResourceManager.GetString("FileDialog_SelectMp4", resourceCulture);
            }
        }

        internal static string FileDialog_SaveGif {
            get {
                return ResourceManager.GetString("FileDialog_SaveGif", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll static image.
        /// </summary>
        internal static string Button_ScrollStaticImage {
            get {
                return ResourceManager.GetString("Button_ScrollStaticImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlay GIF over GIF.
        /// </summary>
        internal static string Button_OverlayGif {
            get {
                return ResourceManager.GetString("Button_OverlayGif", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resize / re-FPS GIF.
        /// </summary>
        internal static string Button_ResizeNfpsGif {
            get {
                return ResourceManager.GetString("Button_ResizeNfpsGif", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp.
        /// </summary>
        internal static string FileDialog_ImageFilter {
            get {
                return ResourceManager.GetString("FileDialog_ImageFilter", resourceCulture);
            }
        }

        internal static string ScrollDialog_Title {
            get {
                return ResourceManager.GetString("ScrollDialog_Title", resourceCulture);
            }
        }

        internal static string ScrollDialog_InputLabel {
            get {
                return ResourceManager.GetString("ScrollDialog_InputLabel", resourceCulture);
            }
        }

        internal static string ScrollDialog_OutputLabel {
            get {
                return ResourceManager.GetString("ScrollDialog_OutputLabel", resourceCulture);
            }
        }

        internal static string ScrollDialog_Direction {
            get {
                return ResourceManager.GetString("ScrollDialog_Direction", resourceCulture);
            }
        }

        internal static string ScrollDialog_Step {
            get {
                return ResourceManager.GetString("ScrollDialog_Step", resourceCulture);
            }
        }

        internal static string ScrollDialog_Duration {
            get {
                return ResourceManager.GetString("ScrollDialog_Duration", resourceCulture);
            }
        }

        internal static string ScrollDialog_MoveCount {
            get {
                return ResourceManager.GetString("ScrollDialog_MoveCount", resourceCulture);
            }
        }

        internal static string ScrollDialog_FullCycle {
            get {
                return ResourceManager.GetString("ScrollDialog_FullCycle", resourceCulture);
            }
        }

        internal static string ScrollDialog_Browse {
            get {
                return ResourceManager.GetString("ScrollDialog_Browse", resourceCulture);
            }
        }

        internal static string ScrollDialog_OK {
            get {
                return ResourceManager.GetString("ScrollDialog_OK", resourceCulture);
            }
        }

        internal static string ScrollDialog_Cancel {
            get {
                return ResourceManager.GetString("ScrollDialog_Cancel", resourceCulture);
            }
        }

        internal static string ScrollDialog_SelectInput {
            get {
                return ResourceManager.GetString("ScrollDialog_SelectInput", resourceCulture);
            }
        }

        internal static string ScrollDialog_SelectOutput {
            get {
                return ResourceManager.GetString("ScrollDialog_SelectOutput", resourceCulture);
            }
        }

        internal static string ScrollDialog_InputRequired {
            get {
                return ResourceManager.GetString("ScrollDialog_InputRequired", resourceCulture);
            }
        }

        internal static string ScrollDialog_OutputRequired {
            get {
                return ResourceManager.GetString("ScrollDialog_OutputRequired", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirRight {
            get {
                return ResourceManager.GetString("ScrollDialog_DirRight", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirLeft {
            get {
                return ResourceManager.GetString("ScrollDialog_DirLeft", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirDown {
            get {
                return ResourceManager.GetString("ScrollDialog_DirDown", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirUp {
            get {
                return ResourceManager.GetString("ScrollDialog_DirUp", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirLeftUp {
            get {
                return ResourceManager.GetString("ScrollDialog_DirLeftUp", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirLeftDown {
            get {
                return ResourceManager.GetString("ScrollDialog_DirLeftDown", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirRightUp {
            get {
                return ResourceManager.GetString("ScrollDialog_DirRightUp", resourceCulture);
            }
        }

        internal static string ScrollDialog_DirRightDown {
            get {
                return ResourceManager.GetString("ScrollDialog_DirRightDown", resourceCulture);
            }
        }

        internal static string Warning_FPS_Mismatch {
            get {
                return ResourceManager.GetString("Warning_FPS_Mismatch", resourceCulture);
            }
        }

        // Concatenate Dialog Resources
        internal static string ConcatenateDialog_Title {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Title", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_Instructions {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Instructions", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_GifFiles {
            get {
                return ResourceManager.GetString("ConcatenateDialog_GifFiles", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_AddFiles {
            get {
                return ResourceManager.GetString("ConcatenateDialog_AddFiles", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_Remove {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Remove", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_MoveUp {
            get {
                return ResourceManager.GetString("ConcatenateDialog_MoveUp", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_MoveDown {
            get {
                return ResourceManager.GetString("ConcatenateDialog_MoveDown", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_FpsSettings {
            get {
                return ResourceManager.GetString("ConcatenateDialog_FpsSettings", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_PaletteSettings {
            get {
                return ResourceManager.GetString("ConcatenateDialog_PaletteSettings", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_FpsAutoHighest {
            get {
                return ResourceManager.GetString("ConcatenateDialog_FpsAutoHighest", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_FpsUseReference {
            get {
                return ResourceManager.GetString("ConcatenateDialog_FpsUseReference", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_FpsCustom {
            get {
                return ResourceManager.GetString("ConcatenateDialog_FpsCustom", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_PaletteAutoMerge {
            get {
                return ResourceManager.GetString("ConcatenateDialog_PaletteAutoMerge", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_PaletteUseReference {
            get {
                return ResourceManager.GetString("ConcatenateDialog_PaletteUseReference", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_OutputFile {
            get {
                return ResourceManager.GetString("ConcatenateDialog_OutputFile", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_Browse {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Browse", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_Concatenate {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Concatenate", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_Cancel {
            get {
                return ResourceManager.GetString("ConcatenateDialog_Cancel", resourceCulture);
            }
        }

        // Transition Dialog Resources
        internal static string TransitionDialog_TransitionSettings {
            get {
                return ResourceManager.GetString("TransitionDialog_TransitionSettings", resourceCulture);
            }
        }

        internal static string TransitionDialog_NoTransition {
            get {
                return ResourceManager.GetString("TransitionDialog_NoTransition", resourceCulture);
            }
        }

        internal static string TransitionDialog_Fade {
            get {
                return ResourceManager.GetString("TransitionDialog_Fade", resourceCulture);
            }
        }

        internal static string TransitionDialog_Slide {
            get {
                return ResourceManager.GetString("TransitionDialog_Slide", resourceCulture);
            }
        }

        internal static string TransitionDialog_Zoom {
            get {
                return ResourceManager.GetString("TransitionDialog_Zoom", resourceCulture);
            }
        }

        internal static string TransitionDialog_Dissolve {
            get {
                return ResourceManager.GetString("TransitionDialog_Dissolve", resourceCulture);
            }
        }

        internal static string TransitionDialog_Left {
            get {
                return ResourceManager.GetString("TransitionDialog_Left", resourceCulture);
            }
        }

        internal static string TransitionDialog_Right {
            get {
                return ResourceManager.GetString("TransitionDialog_Right", resourceCulture);
            }
        }

        internal static string TransitionDialog_Up {
            get {
                return ResourceManager.GetString("TransitionDialog_Up", resourceCulture);
            }
        }

        internal static string TransitionDialog_Down {
            get {
                return ResourceManager.GetString("TransitionDialog_Down", resourceCulture);
            }
        }

        internal static string TransitionDialog_ZoomIn {
            get {
                return ResourceManager.GetString("TransitionDialog_ZoomIn", resourceCulture);
            }
        }

        internal static string TransitionDialog_ZoomOut {
            get {
                return ResourceManager.GetString("TransitionDialog_ZoomOut", resourceCulture);
            }
        }

        internal static string TransitionDialog_TransitionDuration {
            get {
                return ResourceManager.GetString("TransitionDialog_TransitionDuration", resourceCulture);
            }
        }

        internal static string TransitionDialog_Seconds {
            get {
                return ResourceManager.GetString("TransitionDialog_Seconds", resourceCulture);
            }
        }

        internal static string TransitionDialog_PreviewTransition {
            get {
                return ResourceManager.GetString("TransitionDialog_PreviewTransition", resourceCulture);
            }
        }

        internal static string TransitionDialog_Cancel {
            get {
                return ResourceManager.GetString("TransitionDialog_Cancel", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_FrameInfoLabel {
            get {
                return ResourceManager.GetString("ConcatenateDialog_FrameInfoLabel", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_AutoPreview {
            get {
                return ResourceManager.GetString("ConcatenateDialog_AutoPreview", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_StrongPaletteWeightingShort {
            get {
                return ResourceManager.GetString("ConcatenateDialog_StrongPaletteWeightingShort", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_TransitionDurationLabel {
            get {
                return ResourceManager.GetString("ConcatenateDialog_TransitionDurationLabel", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_SecondsLabel {
            get {
                return ResourceManager.GetString("ConcatenateDialog_SecondsLabel", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_PreviewGroup {
            get {
                return ResourceManager.GetString("ConcatenateDialog_PreviewGroup", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_TransitionSlide {
            get {
                return ResourceManager.GetString("ConcatenateDialog_TransitionSlide", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_TransitionZoom {
            get {
                return ResourceManager.GetString("ConcatenateDialog_TransitionZoom", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_TransitionDissolve {
            get {
                return ResourceManager.GetString("ConcatenateDialog_TransitionDissolve", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_PreviewTransition {
            get {
                return ResourceManager.GetString("ConcatenateDialog_PreviewTransition", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_CancelPreview {
            get {
                return ResourceManager.GetString("ConcatenateDialog_CancelPreview", resourceCulture);
            }
        }

        internal static string GTMainForm_ConcatenateGifs {
            get {
                return ResourceManager.GetString("GTMainForm_ConcatenateGifs", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_NoPreviewAvailable {
            get {
                return ResourceManager.GetString("ConcatenateDialog_NoPreviewAvailable", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_UnifyDimensions {
            get {
                return ResourceManager.GetString("ConcatenateDialog_UnifyDimensions", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_UseFasterPalette {
            get {
                return ResourceManager.GetString("ConcatenateDialog_UseFasterPalette", resourceCulture);
            }
        }

        internal static string ConcatenateDialog_UseGifsicleOptimization {
            get {
                return ResourceManager.GetString("ConcatenateDialog_UseGifsicleOptimization", resourceCulture);
            }
        }
    }
}
